A: piano
B: dog_vocalization
C: human_speech
D: flute
E: organ
F: classical_guitar
G: violin
H: trumpet
I: clarinet
J: alto_saxophone
K: drums
L: cat_meow
M: cow_moo
N: frog_croak
O: crow_call
P: glass_breaking
Q: car_horn
R: baby_crying
S: door_slam
T: alarm
